---
- hosts: webservers
  roles: 
    - common
    - apache

- hosts: ci_servers
  roles:
    - git
    - geerlingguy.jenkins
    - jenkins.jobs

- hosts: windows_build_servers
  roles:
      - unity3d
