- name: Create login credentials
  command: java -jar {{ jenkins_jar_location }} -s http://localhost:8080 login --username {{ jenkins_admin_username }} --password {{ jenkins_admin_password }}

- name: Create temporary templates folder
  file: path=/var/lib/jenkins/tmp_templates state=directory mode=0755

- name: Copy seed template to host
  copy: src=../templates/create_seed.xml dest=/var/lib/jenkins/tmp_templates/create_seed.xml

- name: Check for existing seed job
  shell: java -jar {{ jenkins_jar_location }} -s http://localhost:8080/ list-jobs
  register: jenkins_jobs

- name: Create seed job
  shell: java -jar {{ jenkins_jar_location }} -s http://localhost:8080 create-job seed_job < /var/lib/jenkins/tmp_templates/create_seed.xml
  ignore_errors: yes
  when: jenkins_jobs.stdout.find('seed_job') != -1

- name: Delete temporary templates folder
  file: path=/var/lib/jenkins/tmp_templates state=absent